accounts:
  - name: vuser
    coins: ["5000000000000000ubnt"]
  - name: sync
    coins: ["100000000ubnt"]
  - name: binance
    coins: ["50000000000ubnt"]
  - name: nft
    coins: ["1000000000000ubnt"]
validator:
  name: vuser
  staked: "100000000ubnt"
init:
  app:
    "minimum-gas-prices": "0.002ubnt"
    "api.address": "tcp://0.0.0.0:1317"
    "api.rpc-max-body-bytes": 200000000
  config:
    "consensus.timeout_propose": "3s"
    "consensus.timeout_commit": "5s"
    "p2p.addr_book_strict": false
    "p2p.max_num_inbound_peers": 100
    "p2p.max_num_outbound_peers": 100
    "p2p.laddr": "tcp://0.0.0.0:26656"
    "rpc.max_subscriptions_per_client": 20
    "rpc.laddr": "tcp://0.0.0.0:26657"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ubnt"
    synchronizer:
        sourceList:
          - creator: "config.yml"
            name: "binance"
            url: "https://data-seed-prebsc-1-s1.binance.org:8545"

