accounts:
  - name: vuser
    coins: ["5000000000000000ubnt"]
  - name: alice
    coins: ["100000000ubnt"]
  - name: bob
    coins: ["500ubnt"]
validator:
  name: alice
  staked: "100000000ubnt"
client:
  vuex:
    path: "model"
init:
  home: "~/.curium2"
  config:
    "consensus.timeout_propose": "3s"
    "consensus.timeout_commit": "5s"
    "p2p.addr_book_strict": false
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ubnt"
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9091"
  api: ":1318"
  frontend: ":8081"
  dev-ui: ":12346"
